name: GitVDS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest


    steps:
    - name: Ngrok & NSSM İndiriliyor...
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/ntrdnm1/gettovds/main/Files/nssm.exe -OutFile nssm.exe
    - name: NSSM ve Ngrok Windows Dizinine Kopyalanıyor...
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Ngrok Hesabınız Bağlanılıyor...
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Önemli Dosyalar İndiriliyor...
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/ntrdnm1/gettovds/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/CodingHaveGO/gitvds-gamelesscode/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/ntrdnm1/gettovds/main/Files/loop.bat -OutFile loop.bat
    - name:  Ngrok İçin YML Dosyası Oluşturuluyor...
      run: start NGROK-US.bat
    - name: RDP Erişimi Aktif Ediliyor...
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tünel Oluşturuluyor...
      run: sc start ngrok
    - name: VDS Bilgileriniz Hazır!
      run: cmd /c NGROK-CHECK.bat
    - name: Harika! Bu sayfayı kapatabilirsin!
      run: cmd /c loop.bat 
      
